site_name: The Donatinator
site_url: http://donatinator.org
site_description: A small, simple, secure way to accept Single or Recurring Donations for your charities and non-profits.
site_author: Andrew Chilton

repo_url: https://gitlab.com/donatinator/donatinator

pages:
- Home: index.md
- User Guide:
    - Getting Started: user/getting-started.md
    - Single Donations: user/single-donations.md
    - Recurring Donations: user/recurring-donations.md
    - Campaigns: user/campaigns.md
    - Fundraising: user/fundraising.md
    - Admin: user/admin.md
    - Terminology: user/terminology.md
- Technical Guide:
    - Considerations: tech/considerations.md
    - Hosting: tech/hosting.md
    - Environment: tech/environment.md
    - Themes: tech/themes.md
    - Plugins: tech/plugins.md
- Project:
    - Features: project/features.md
    - RoadMap: project/roadmap.md
    - Release Notes: project/release-notes.md
    - Contributing: project/contributing.md
    - RFCs: project/rfcs.md
    - Code of Conduct: project/code-of-conduct.md
    - License: project/license.md
- About:
    - Why a Donor Portal?: about/why.md
    - FAQ: about/faq.md
    - Contact: about/contact.md

site_dir: html

copyright: Copyright &copy; 2017 <a href="https://twitter.com/andychilton">Andrew Chilton</a>.
